#!/usr/bin/env bash

usage() {
	MAIN_BRANCH=$(git config --get shipgit.branch.main)
	PRODUCTION_BRANCH=$(git config --get shipgit.branch.production)
	echo "usage: shipgit update"
  echo "This will pull latest changes from remote $MAIN_BRANCH and $PRODUCTION_BRANCH."
}

cmd_help() {
	usage
  exit 0
}

cmd_default() {
  local initialized=$(git config --get shipgit.initialized)
	if [ "$initialized" != "true" ]; then
		echo "+++++++++++++++++++++++ ATTENTION +++++++++++++++++++++++"
		echo ""
    echo "shipgit can only be used inside a shipgit initialized directory."
    echo "Run shipgit init to initialize."
		echo ""
		echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
		exit 0
	fi

	CURRENT_BRANCH=$(git branch --show-current)
	MAIN_BRANCH=$(git config --get shipgit.branch.main)
	PRODUCTION_BRANCH=$(git config --get shipgit.branch.production)

	echo "========================== Syncing =========================="
	echo ""
	echo "Steps:"

	git checkout -q "$MAIN_BRANCH" &> /dev/null
	git pull origin "$MAIN_BRANCH" &> /dev/null
	git fetch --tags &> /dev/null
	echo "    1. Pulled latest changes from remote $MAIN_BRANCH."

	git checkout -q "$PRODUCTION_BRANCH" &> /dev/null
	git pull origin "$PRODUCTION_BRANCH" &> /dev/null
	git fetch --tags &> /dev/null
	echo "    2. Pulled latest changes from remote $PRODUCTION_BRANCH."

	git checkout -q "$CURRENT_BRANCH" &> /dev/null
	echo ""
	echo "============================================================="
}
